### ISSUE TITLE
NSFW Errors

### ISSUE THREAD

**Issue by imagine-erik** [BatouResearch/Cog-Outpaint-SDXL#2]
We've been using this model on Replicate fairly consistently over the last month. Just recently, we started seeing NSFW errors. I've attached an example but the model simply does not return all the requested image iterations. We end up paying full price for this and there is nothing in prompt at all to trigger NSFW content. Furthermore, we're not providing any prompt whatsoever because we're simply trying to extend the edges of the image to fit a new aspect ratio. We have never seen any NSFW content be returned by this model either. This seems like an error that was introduced. Can this be fixed?

**Comment by asiryan** [comment]
> We've been using this model on Replicate fairly consistently over the last month. Just recently, we started seeing NSFW errors. I've attached an example but the model simply does not return all the requested image iterations. We end up paying full price for this and there is nothing in prompt at all to trigger NSFW content. Furthermore, we're not providing any prompt whatsoever because we're simply trying to extend the edges of the image to fit a new aspect ratio. We have never seen any NSFW content be returned by this model either. This seems like an error that was introduced. Can this be fixed?

Agreed. Please disable the NSFW check or make it possible via API. I have lots of errors too.

**Comment by Pau-Lozano** [comment]
Hi there, due to having a lot on my plate currently, I'm no longer maintaining this project.
However, I'm happy to accept PRs if you want to solve it yourself.
