### ISSUE TITLE
Original image is being manipulated

### ISSUE THREAD

**Issue by imagine-erik** [BatouResearch/Cog-Outpaint-SDXL#3]
We're seeing that the original image is being manipulated in addition to the new outpainted areas of the image. We're seeing a loss of detail (blurriness), color changes and more. The original image should be left untouched by the model and simply outpaint or extend the edges. This is how Photoshop generative expand works. We'd love to see this fixed as the model works fantastically otherwise.

**Comment by asiryan** [comment]
> We're seeing that the original image is being manipulated in addition to the new outpainted areas of the image. We're seeing a loss of detail (blurriness), color changes and more. The original image should be left untouched by the model and simply outpaint or extend the edges. This is how Photoshop generative expand works. We'd love to see this fixed as the model works fantastically otherwise.

Agreed. Please disable the NSFW check or make it possible via API. I have lots of errors too.

**Comment by asiryan** [comment]
> We're seeing that the original image is being manipulated in addition to the new outpainted areas of the image. We're seeing a loss of detail (blurriness), color changes and more. The original image should be left untouched by the model and simply outpaint or extend the edges. This is how Photoshop generative expand works. We'd love to see this fixed as the model works fantastically otherwise.

Could you share any examples?

**Comment by Pau-Lozano** [comment]
This is most likely due to the auto encoder of SDXL, there isn't much I can do about it.
However, feel free to try fixing it and send a PR.

**Comment by imagine-erik** [comment]
@Pau-Lozano o1 suggested the changes in the PR I just made. It suggested to keep the entire process latent until the very end, which should help reduce the visual artifacts introduced by multiple VAE encode-decode cycles. Can you check it out and let me know what you think?
